name: Convert BunnyLOL JavaScript files for Browser
on: [push]

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@master
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - name: Convert from Flow to Browser JS, bundle and minify files
        run: |
          npm install
          npm run build 
          npm run bundle
          npm run minify
          echo "Minified files"
      - name: Commit changes to web
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Build for Web" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PUSH_TOKEN }}
